---
- name: "populate service facts"
  ansible.builtin.service_facts:

- name: "stop node-exporter"
  ansible.builtin.systemd:
    daemon_reload: false
    name: node_exporter
    enabled: false
    state: stopped
  when: "'node_exporter.service' in services"

- name: "remove node-exporter service"
  ansible.builtin.file:
    path: "/etc/systemd/system/node_exporter.service"
    state: absent
  when: "'node_exporter.service' in services"

- name: "ensure systemd is reloaded"
  ansible.builtin.systemd:
    daemon_reload: true
  when: "'node_exporter.service' in services"

- name: "purge node-exporter"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ node_exporter_path }}"
    - "/etc/node-exporter"
